name: dcat
description: A dart version of the Unix cat command.
version: 1.0.1
repository: https://github.com/ElanDeyan/dcat
issue_tracker: https://github.com/ElanDeyan/dcat/issues
executables: 
  dcat:

topics:
  - cli

platforms:
  windows: null
  macos: null
  linux: null

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.5.0
  characters: ^1.3.0
  quiver: ^3.2.2

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^6.0.0
