name: dcat
description: A dart version of the Unix cat command
version: 0.0.1
repository: https://github.com/ElanDeyan/dcat

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
